### ISSUE TITLE
Issues with the new UI

### ISSUE THREAD

**Issue by lodewykk** [nsand/tab-glutton#28]
I personally find the new UI less easy to read and navigate in.

Issues: 
- Too sparse (lots of white space) (too few tabs shown at a time)
- No clear delimiter between tabs (they're now just lines of text, where they used to be nice buttons) - This places a higher processing burden on the unconscious mind, making quick recognition and mental grouping of tabs slower and less efficient. 
- The view jumps on tab closure, making one lose place in the list. When near the top of the list the top few tabs seem to remain in the same place, but further down everything seems to scroll up (or down, I can't tell). It might be that it just sometimes jumps up, and sometimes down. 
- Window order is often incorrect. The oldest window used to be displayed just below the current window, but now might be at the bottom, depending on which window one is at. Consistent window and tab order is very important for maintaining a manageable overview over a large grouping of windows and tabs.

**Comment by nsand** [comment]
Hi, @lodewykk . Thanks, as always, for your attention to detail and for taking the time to open these issues.

I'm following [Google's material design](https://material.google.com/components/lists.html#lists-specs) (or at least trying to capture as much of it as possible). The design does lend itself to being a bit more sparse, as it uses intentional whitespace to

> create a bold and graphic interface that immerse the user in the experience.

-- [Material Design Introduction](https://material.google.com/#introduction-principles)

The language does appear to have some guidelines around separators between list elements, but it seems that it would add even more height to each item (another 12 pixels). It could possibly be something that I add as an option so that each tab item is more defined.

I see what you're saying about the window jumping around when closing tabs. Damn that's annoying. I'll see if I can fix that quickly, and the solution may basically involve fixing your final point of the window order being incorrect. I'll make the windows so they're in order of usage, and then defaulting to a deterministic order if they've never been focused in your session. I hope that should fix both problems.

**Comment by nsand** [comment]
I've hopefully addressed the window ordering issues in version 2.0.2.

**Comment by nsand** [comment]
I've pushed 3706048fa2798d05a2b7f695cd4477492b76df10 and uploaded version 2.1.1 of Tab Glutton, which provides options around providing more contrast between tabs in the list (either as cards, or with separators between each line). I didn't do anything to remove the spacing as this is part of the design language. Hopefully this is alright.

**Comment by lodewykk** [comment]
A bit of a late update here, but the issue seems to still be open. I believe the issues listed have been resolved.
